### ISSUE TITLE
Configurer/Deployer Linkerd

### ISSUE THREAD

**Issue by ThomasCardin** [ClubCedille/Plateforme-Cedille#32]

**Comment by ThomasCardin** [comment]
Voici des erreurs en liens avec notre problème d'installation de Linkerd.

https://github.com/linkerd/linkerd2/issues/10994
https://github.com/linkerd/linkerd2/issues/11156

**Comment by Simon-Boyer** [comment]
Ne sera pas fait car on utilisera Kuma a la place
